### ISSUE TITLE
There is an error in the code of Chapter03 reading 'frankenstein.txt'

### ISSUE THREAD

**Issue by Pearapon** [PacktPublishing/Network-Science-with-Python-and-NetworkX-Quick-Start-Guide#1]
# Read the text
with open(data_dir / 'shelley1818' / 'frankenstein.txt') as f:
    text = f.read()
# Create a network from the text
G = co_occurrence_network(text)

========================

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-39-3557280a0232> in <module>
      1 # Read the text
      2 with open(data_dir / 'shelley1818' / 'frankenstein.txt') as f:
----> 3     text = f.read()
      4 # Create a network from the text
      5 G = co_occurrence_network(text)

C:\ProgramData\Anaconda3\lib\encodings\cp874.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x99 in position 3296: character maps to <undefined>

**Comment by elplatt** [comment]
Ah, which OS and version of python you're using?

**Comment by Pearapon** [comment]
My OS is “Windows 8.1 Pro”

 

Regards

Pearapon S.

Bangkok, Thailand

**Comment by elplatt** [comment]
Can you try changing the line to the following and let me know if it works?

    with open(data_dir / 'shelley1818' / 'frankenstein.txt', encoding='utf-8') as f:
